name: Compile and upload birdy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - uses: actions/upload-artifact@v4
    - uses: actions/upload-artifact@v4
      with:
        name: birdy
        path: birdy
