name: Compile and upload birdy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        sudo add-apt-repository -y ppa:team-xbmc/ppa
        sudo apt-get update
        sudo apt-get install -y nlohmann-json3-dev curl libargs-dev

    - name: Build
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: birdy
        path: birdy
